# Generated by Django 4.1 on 2023-11-02 09:33

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="필수", max_length=200, unique=True, verbose_name="이메일"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(help_text="필수", max_length=100, verbose_name="이름"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                help_text="필수",
                max_length=11,
                unique=True,
                validators=[users.validators.PhoneNumberValidator()],
                verbose_name="전화번호",
            ),
        ),
    ]
